kind: Deployment
apiVersion: apps/v1
metadata:
   name: hpa-deployment
spec:
   replicas: 1
   selector:
    matchLabels:
     name: deployment
   template:
     metadata:
       name: skillrary
       labels:
         name: deployment
     spec:
      containers:
        - name: abc
          image: httpd
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
