apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: pv-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      volumes:
      - name: pv
        persistentVolumeClaim:
          claimName: pvc-nfs-pv1
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: pv
          mountPath: /usr/share/nginx/html
