apiVersion: v1
kind: Pod
metadata:
  name: my-emptydir-pod
spec:
  containers:
  - name: one
    image: centos
    command: ["/bin/bash", "-c", "echo learning k8s volumes > /bharath/k8s.txt && sleep 3600"]
    volumeMounts:
    - name: my-emptydir-vol
      mountPath: "/bharath"
  - name: two
    image: centos
    command: ["/bin/bash", "-c", "sleep 3600"]
    volumeMounts:
    - name: my-emptydir-vol
      mountPath: "/bharath"
  volumes:
  - name: my-emptydir-vol
    emptyDir: {}
