
---
kind: Deployment
apiVersion: apps/v1
metadata:
   name: cluster-ip-deployment
spec:
   replicas: 2
   selector:
    matchLabels:
     name: deployment
   template:
     metadata:
       name: happy
       labels:
         name: deployment
     spec:
      containers:
        - name: abcd
          image: httpd
          ports:
          - containerPort: 80



---
kind: Service    
apiVersion: v1
metadata:
  name: clusterip
spec:
  ports:
    - port: 80         
      targetPort: 80   
  selector:
    name: deployment  
  type: ClusterIP   
  
  
