---
kind: Service
apiVersion: v1
metadata:
  name: nodeport-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: deployment
  type: NodePort



---
kind: Deployment
apiVersion: apps/v1
metadata:
   name: nodeport-deploy
spec:
   replicas: 2
   selector:
    matchLabels:
     name: deployment
   template:
     metadata:
       name: happy
       labels:
         name: deployment
     spec:
      containers:
        - name: abcd
          image: nginx
          ports:
          - containerPort: 80
