apiVersion: v1
kind: Pod
metadata:
  name: ruby-app-with-adapter
spec:
  containers:
  - name: app
    image: ruby:2.7
    command: ["sh", "-c", "while true; do echo $(date) - $(hostname) - $((RANDOM % 10 + 1)) >> /app/logs/ruby-app.log; sleep 2; done"]
    volumeMounts:
    - name: log-volume
      mountPath: /app/logs
  - name: adapter
    image: ubuntu:latest
    command: ["sh", "-c", "while true; do echo RUBY - $(hostname) - $(tail -n 1 /app/logs/ruby-app.log); sleep 2; done"]
    volumeMounts:
    - name: log-volume
      mountPath: /app/logs
  volumes:
  - name: log-volume
    emptyDir: {}


1) Copy the above YAML manifest into a file named ruby.yml.

2) Apply the YAML manifest by running the following command
$ kubectl apply -f ruby.yml

3) Check the status of the Pod by running
$ kubectl get pods

4) Once the Pod is running, you can view the logs of the adapter container using the following command
kubectl logs ruby-app-with-adapter -c adapter

5) You can also view the logs of the application container using the following command
kubectl logs ruby-app-with-adapter -c app
