apiVersion: batch/v1
kind: Job
metadata:
  name: pod-job-parallel
spec:
  parallelism: 5                          
  activeDeadlineSeconds: 10  
  template:
    metadata:
      name: my-parallel
    spec:
      containers:
      - name: xyz
        image: centos:7
        command: ["bin/bash", "-c", "echo Hello World; sleep 20"]
      restartPolicy: Never
