apiVersion: v1
kind: Pod
metadata:
  name: multi-cont-pod
spec:
  containers:
    - name: cont-1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo container-1 is running; sleep 5 ; done"]

    - name: cont-2
      image: centos
      command: ["/bin/bash", "-c", "while true; do echo container-2 is running; sleep 5 ; done"]
